version: '3'

services:
  playwright-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DISPLAY=:99
      - PLAYWRIGHT_HEADLESS_MODE=false
    volumes:
      - ./debug:/app/debug
    restart: unless-stopped